// bind with ipcMain.handle
export const IPCActions = {
  APP: {
    GET_APP_PATH: 'APP:GET_APP_PATH',
    GET_WORK_SPACE: 'APP:GET_WORK_SPACE',
    GET_RECENT_WORK_SPACES: 'APP:GET_RECENT_WORK_SPACES',
    SET_WORK_SPACE: 'APP:SET_WORK_SPACE',
    PUSH: {
      WORK_SPACE_CHANGED: 'APP:PUSH:WORK_SPACE_CHANGED',
      RECENT_WORK_SPACES_CHANGED: 'APP:PUSH:RECENT_WORK_SPACES_CHANGED',
    },
  },
  DIALOG: {
    SHOW_MESSAGE_DIALOG: 'DIALOG:SHOW_MESSAGE_DIALOG',
    SHOW_SELECTION_DIR: 'DIALOG:SHOW_SELECTION_DIR',
  },
  MENU: {
    SHOW_FILE_OPERATION_MENU: 'MENU:SHOW_FILE_OPERATION_MENU',
    PUSH: {
      RENAME_SELECTED_FILE: 'MENU:PUSH:RENAME_SELECTED_FILE',
      FILES_DELETED: 'MENU:PUSH:FILES_DELETED', // not in use
    },
  },
  DATA: {
    //app data
    // Search bar
    SET_NEW_SEARCH_TARGET: 'DATA:SET_NEW_SEARCH_TARGET',
    // opened files
    GET_ALL_OPENED_FILES: 'DATA:GET_ALL_OPENED_FILES',
    PUSH_ALL_OPENED_FILES: 'DATA:PUSH_ALL_OPENED_FILES', //like the previous one but push to all listening component in the renderer
    UPDATE_OPENED_FILE_CONTENT: 'FILES:UPDATE_OPENED_FILE_CONTENT', //render to main
    CLOSE_TARGET_OPENED_FILES: 'DATA:CLOSE_OPENED_FILES',
    CLOSE_ALL_OPENED_FILES: 'DATA:CLOSE_ALL_OPENED_FILES',
    // selection status
    GET_SELECTION_STATUS_CACHE: 'DATA:GET_SELECTION_STATUS_CACHE',
    UPDATE_SELECTION_STATUS_CACHE: 'DATA:UPDATE_SELECTION_STATUS_CACHE',
    // active file
    CHANGE_ACTIVE_FILE: 'FILES:CHANGE_ACTIVE_FILE',
    // saving
    SAVE_ACTIVE_FILE: 'FILE:SAVE_ACTIVE_FILE',
    SAVE_ALL_OPENED_FILES: 'FILE:SAVE_ALL_OPENED_FILES',
    SAVE_TARGET_OPENED_FILE: 'FILE:SAVE_TARGET_FILE',
    // Deleting - currently no IPC interface, only context memu
    PUSH: {
      ACTIVE_FILE_CHANGED: 'FILES:PUSH:ACTIVE_FILE_CHANGED',
      OPENED_FILE_CONTENT_CHANGED: 'FILES:PUSH:OPENED_FILE_CONTENT_CHANGED', //main to render
      OPENED_FILES_CHANGED: 'DATA:PUSH:OPENED_FILES_CHANGED', // main to rendered, similar to server side pushing
      BEGIN_NEW_SEARCH: 'DATA:PUSH:FOCUS_SEARCH_BAR', // push the target type for search bar
    },
  },
  FILES: {
    //Generic FS
    LIST_CURRENT_PATH: 'FILES:LIST_CURRENT_PATH',
    LIST_CURRENT_PATH_MD: 'FILES:LIST_CURRENT_PATH_MD',
    // tags
    LIST_ALL_TAGS: 'FILES:LIST_ALL_TAGS',
    CREATE_NEW_FILE: 'FILES:CREATE_NEW_FILE',
    CREATE_NEW_TAG: 'FILES:CREATE_NEW_TAG',
    READ_MD_FROM_PATH: 'FILES:READ_MD_FROM_PATH',
    // renaming
    CHANGE_TARGET_FILE_NAME: 'FILE:CHANGE_TARGET_FILE_NAME', //generic interface that will be used by renderer
    PUSH: {
      RENAMING_TARGET_FILE: 'FILE:RENAMING_TARGET_FILE', //send to renderer along with target file info
    },
    // signals don't send a payload
    SIGNAL: {
      MD_LIST_CHANGED: 'FILES:SIGNAL:MD_LIST_CHANGED',
      TAG_LIST_CHANGED: 'FILES:SIGNAL:TAG_LIST_CHANGED',
    },
  },
};
