// bind with ipcMain.handle
export const IPCActions = {
  APP: {
    GET_APP_PATH: 'APP:GET_APP_PATH',
  },
  DIALOG: {
    SHOW_SELECTION_DIR: 'DIALOG:SHOW_SELECTION_DIR',
  },
  DATA: {
    GET_ALL_OPENED_FILES: 'DATA:GET_ALL_OPENED_FILES',
    PUSH_ALL_OPENED_FILES: 'DATA:PUSH_ALL_OPENED_FILES',
    CLOSE_OPENED_FILES: 'DATA:CLOSE_OPENED_FILES',
    PUSH: {
      OPENED_FILES_CHANGED: 'DATA:PUSH:PUSH_OPENED_FILES_CHANGED', // main to rendered, similar to server side pushing
    },
  },
  FILES: {
    OPENED_FILE_CHANGED: 'FILES:OPENED_FILE_CHANGED',
    LIST_CURRENT_PATH: 'FILES:LIST_CURRENT_PATH',
    LIST_CURRENT_PATH_MD: 'FILES:LIST_CURRENT_PATH_MD',
    READ_MD_PATH: 'FILES:READ_MD_PATH',
    CHANGE_FILE_CONTENT: 'FILES:CHANGE_FILE_CONTENT', //render to main
    CHANGE_ACTIVE_FILE: 'FILES:CHANGE_ACTIVE_FILE',
    PUSH: {
      ACTIVE_FILE_CHANGED: 'FILES:PUSH:ACTIVE_FILE_CHANGED',
      FILE_CONTENT_CHANGED: 'FILES:PUSH:FILE_CONTENT_CHANGED', //main to render
    },
  },
};
